services:
  ml_part:
    build: ./ml_part
    volumes: 
      - ./ml_part:/app
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1 
    env_file:
      - ./ml_part/env
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4096M
    restart: always
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: naim
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: naimix
    volumes:
      - pg_data:/var/lib/postgresql/data 
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 6000M
    restart: always
    
volumes:
  pg_data: