services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - rb_front_node_modules:/app/node_modules
    ports:
      - '80:80'
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2000M
    restart: always
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4096M
    restart: always
  ml_part:
    build: ./ml_part
    volumes: 
      - ./ml_part:/app
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1 
    env_file:
      - ./ml_part/.env
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4096M
    restart: always
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: naim
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: naimix
    volumes:
      - pg_data:/var/lib/postgresql/data 
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 6000M
    restart: always
    
volumes:
  rb_front_node_modules:
  pg_data: