services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1 
    env_file:
      - .env 
